services:
  backend:
    build:
      context: ./django-app
    container_name: smart-garden-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SECURE_SSL_REDIRECT: "False"
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed &&
             gunicorn Plant_plotter_settings.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 180"

  frontend:
    build:
      context: ./react-app
    container_name: smart-garden-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  static_volume:
