# Generated by Django 6.0.2 on 2026-02-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companion_helped_bylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companion_helpslistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('plant_directly', models.BooleanField()),
                ('spacing_between_rows', models.PositiveIntegerField(default=0)),
                ('spacing_in_rows', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('time_to_germinate_indoors_start', models.CharField(max_length=512, null=True)),
                ('time_to_germinate_indoors_end', models.CharField(max_length=512, null=True)),
                ('time_to_germinate_indoors_period', models.PositiveIntegerField(default=0, null=True)),
                ('plant_start', models.CharField(max_length=512)),
                ('plant_end', models.CharField(max_length=512)),
                ('time_first_harvets', models.PositiveIntegerField(default=0, null=True)),
                ('harest_start', models.CharField(max_length=512)),
                ('harest_end', models.CharField(max_length=512)),
                ('companion_helped_by', models.ManyToManyField(blank=True, related_name='plant_helps_by', through='Plant_plotter.Companion_helped_bylistItem', to='Plant_plotter.plant')),
                ('companion_helps', models.ManyToManyField(blank=True, related_name='plant_helps', through='Plant_plotter.Companion_helpslistItem', to='Plant_plotter.plant')),
            ],
        ),
        migrations.AddField(
            model_name='companion_helpslistitem',
            name='other_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_to_helps', to='Plant_plotter.plant'),
        ),
        migrations.AddField(
            model_name='companion_helpslistitem',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_from_helps', to='Plant_plotter.plant'),
        ),
        migrations.AddField(
            model_name='companion_helped_bylistitem',
            name='other_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_to_helps_by', to='Plant_plotter.plant'),
        ),
        migrations.AddField(
            model_name='companion_helped_bylistitem',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_from_helps_by', to='Plant_plotter.plant'),
        ),
        migrations.CreateModel(
            name='Plants_avoidlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('other_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_to_avoid', to='Plant_plotter.plant')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_from_avoid', to='Plant_plotter.plant')),
            ],
            options={
                'unique_together': {('other_plant', 'plant'), ('plant', 'position')},
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='plants_avoid',
            field=models.ManyToManyField(blank=True, related_name='plant_avoids', through='Plant_plotter.Plants_avoidlistItem', to='Plant_plotter.plant'),
        ),
        migrations.AlterUniqueTogether(
            name='companion_helpslistitem',
            unique_together={('other_plant', 'plant'), ('plant', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='companion_helped_bylistitem',
            unique_together={('other_plant', 'plant'), ('plant', 'position')},
        ),
    ]
