# Generated by Django 6.0.2 on 2026-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plant_plotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='harest_end',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harest_start',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_end',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_start',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
