# Generated by Django 6.0.2 on 2026-02-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plant_plotter', '0002_alter_plant_harest_end_alter_plant_harest_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companion_helped_bylistitem',
            unique_together={('other_plant', 'plant')},
        ),
        migrations.AlterUniqueTogether(
            name='companion_helpslistitem',
            unique_together={('other_plant', 'plant')},
        ),
        migrations.AlterUniqueTogether(
            name='plants_avoidlistitem',
            unique_together={('other_plant', 'plant')},
        ),
        migrations.RemoveField(
            model_name='companion_helped_bylistitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='companion_helpslistitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='plants_avoidlistitem',
            name='position',
        ),
    ]
